CREATE TABLE IF NOT EXISTS products(
    id SERIAL PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);